name: Deploy ASP.Net Core app
env:
  DOTNET_VERSION: '6.0.x'
on:
  workflow_dispatch:
    inputs:
      artifact_workflow_number:
        required: true
        description: 'workflow_id where artifacts will be uploaded'
jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          workflow: ci.yml
          run_number: ${{inputs.artifact_workflow_number}}
          workflow_conclusion: success

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
